Animais/Models/AnimaisModels.cs
using System.ComponentModel.DataAnnotations;

namespace Animais.Models
{
    public class AnimaisModels
    {
        public int Id { get; set; }

        [Required(ErrorMessage = "O campo Nome é obrigatório.")]
        public string Nome { get; set; }

        [Required(ErrorMessage = "O campo Idade é obrigatório.")]
        public string Idade { get; set; }

        [Required(ErrorMessage = "O campo Raça é obrigatório.")]
        public string Raça { get; set; }

        [Required(ErrorMessage = "O campo Porte é obrigatório.")]
        public string Porte { get; set; }
    }
}

Animais/Models/ErrorViewModel.cs
namespace Animais.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Animais/Controllers/AnimaisController.cs
using Microsoft.AspNetCore.Mvc;
using Animais.Data;
using Animais.Models;
using System;

namespace Animais.Controllers
{
    public class AnimaisController : Controller
    {
        readonly private ApplicationDbContext _context;

        public AnimaisController()
        {
            var context = new ApplicationDbContext();

            _context = context;
        }
        public IActionResult Index()
        {
            IEnumerable<AnimaisModels> animaisModels = _context.AnimaisModels;
            return View(animaisModels);
        }

        [HttpGet]
        public IActionResult Cadastrar()
        {
            return View();
        }

        [HttpGet]
        public IActionResult Editar(int id)
        {
            AnimaisModels animais = _context.AnimaisModels.FirstOrDefault(x => x.Id == id);
            return View(animais);
        }

        [HttpGet]
        public IActionResult Excluir(int id)
        {
            AnimaisModels animais = _context.AnimaisModels.FirstOrDefault(x => x.Id == id);
            return View(animais);
        }

        [HttpPost]
        public IActionResult Cadastrar(AnimaisModels animaisModels)
        {
            if (ModelState.IsValid)
            {
                _context.Add(animaisModels);
                _context.SaveChanges();

                return RedirectToAction("Index");
            }

            return View(animaisModels);
        }

        [HttpPost]
        public IActionResult Editar(AnimaisModels animaisModels)
        {
            if (ModelState.IsValid)
            {
                _context.Update(animaisModels);
                _context.SaveChanges();


                return RedirectToAction("Index");
            }

            return View(animaisModels);
        }

        [HttpPost]
        public IActionResult Excluir(AnimaisModels animaisModels)

        {
            _context.Remove(animaisModels);
            _context.SaveChanges();

            return RedirectToAction("Index");
        }

    }
}

Animais/Controllers/HomeController.cs
using Animais.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace Animais.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Animais/Views/Animais/Cadastrar.cshtml
@model AnimaisModels;


<form method="post">
    <h2> Cadastrar Pet</h2>
    <div class="form-group">
        <label for="formGroupExampleInput">Nome</label>
        <input type="text" asp-for=Nome class="form-control" id="formGroupExampleInput" placeholder="Example input">
        <span asp-validation-for="Nome" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label for="formGroupExampleInput2">Idade</label>
        <input type="text" asp-for=Idade class ="form-control" id="formGroupExampleInput2" placeholder="Another input">
        <span asp-validation-for="Idade" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label for="formGroupExampleInput2">Raça</label>
        <input type="text" asp-for=Raça class ="form-control" id="formGroupExampleInput2" placeholder="Another input">
        <span asp-validation-for="Raça" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label for="formGroupExampleInput2">Porte</label>
        <input type="text" asp-for=Porte class ="form-control" id="formGroupExampleInput2" placeholder="Another input">
        <span asp-validation-for="Porte" class="text-danger"></span>
    </div>
    <div>
        <button type="submit" class="btn btn-success">Cadastrar</button>
        <a class="btn btn-primary w-30" asp-controller="Animais" asp-action="Index">Voltar</a>
    </div>
</form>

Animais/Views/Animais/Editar.cshtml
@model AnimaisModels;

<h2> Editar Cadastro</h2>

<form method="post">
    <input type="hidden" asp-for="Id"/>

    <div class="form-group">
        <label for="formGroupExampleInput">Nome</label>
        <input type="text" asp-for=Nome class="form-control" id="formGroupExampleInput" placeholder="Example input">
        <span asp-validation-for="Nome" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label for="formGroupExampleInput2">Idade</label>
        <input type="text" asp-for=Idade class="form-control" id="formGroupExampleInput2" placeholder="Another input">
        <span asp-validation-for="Idade" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label for="formGroupExampleInput2">Raça</label>
        <input type="text" asp-for=Raça class="form-control" id="formGroupExampleInput2" placeholder="Another input">
        <span asp-validation-for="Raça" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label for="formGroupExampleInput2">Porte</label>
        <input type="text" asp-for=Porte class="form-control" id="formGroupExampleInput2" placeholder="Another input">
        <span asp-validation-for="Porte" class="text-danger"></span>
    </div>
    <div>
        <button type="submit" class="btn btn-success">Concluir Edição</button>
        <a class="btn btn-primary w-30" asp-controller="Animais" asp-action="Index">Voltar</a>
    </div>
</form>

Animais/Views/Animais/Excluir.cshtml
@model AnimaisModels;

<h2> Excluir Cadastro</h2>

<form method="post">
    <input type="hidden" asp-for="Id" />

    <div class="form-group">
        <label for="formGroupExampleInput">Nome</label>
        <input type="text" asp-for=Nome readonly class="form-control" id="formGroupExampleInput" placeholder="Example input">
    </div>
    <div class="form-group">
        <label for="formGroupExampleInput2">Idade</label>
        <input type="text" asp-for=Idade readonly class="form-control" id="formGroupExampleInput2" placeholder="Another input">
    </div>
    <div class="form-group">
        <label for="formGroupExampleInput2">Raça</label>
        <input type="text" asp-for=Raça readonly class="form-control" id="formGroupExampleInput2" placeholder="Another input">
    </div>
    <div class="form-group">
        <label for="formGroupExampleInput2">Porte</label>
        <input type="text" asp-for=Porte readonly class="form-control" id="formGroupExampleInput2" placeholder="Another input">
    </div>
    <div>
        <button type="submit" class="btn btn-success">Excluir</button>
        <a class="btn btn-primary w-30" asp-controller="Animais" asp-action="Index">Voltar</a>
    </div>
</form>

Animais/Views/Animais/Index.cshtml
@model IEnumerable<AnimaisModels> 


<style>
    .table th:last-child,
    .table td:last-child { width:230px} 
 </style>

<h1>Pets Regastados </h1>

<table class="table table-bordered table-dark">
    <thead>
        <tr>
            <th scope="col">Nome</th>
            <th scope="col">Idade</th>
            <th scope="col">Raça</th>
            <th scope="col">Porte</th>
            <th ></th>

        </tr>
    </thead>
    <tbody>

        @if (Model != null)
        {
            @foreach (var animais in Model)
            {
                <tr>
                    <td>@animais.Nome</td>
                    <td>@animais.Idade</td>
                    <td>@animais.Raça</td>
                    <td>@animais.Porte</td>


                    <td>
                        <a asp-controller="Animais" asp-action="Editar" asp-route-id="@animais.Id" class="btn btn-warning mx-3">Editar</a>
                        <a asp-controller="Animais" asp-action="Excluir" asp-route-id="@animais.Id" class="btn btn-warning mx-3">Excluir</a>
                    </td>
                </tr/>
            }
        }

    </tbody>
</table>


<a class="btn btn-primary" asp-controller="Animais" asp-action="Cadastrar">Cadastrar</a>

Animais/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Animais/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Animais</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Animais.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Animais</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - Animais - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>